### ISSUE TITLE
Nested Arrays - Version 5.0.6

### ISSUE THREAD

**Issue by thomaswelton** [brightmachine/laratash#8]
In my views I used to be able to access variables in deeply nested arrays. `` {{ item.foo.bar.baz }}`` After updating to version 5.0.6 this no longer worked. Reverting back fixed the issue.

Does the latest version support deeply nested arrays?

**Comment by kelvinj** [comment]
We used to do an additional check on data passed in and call `toArray()` on an item if it was an object and had that method defined.

This bit of magic was a bit pointless so now we've reverted to just pass the data through to mustache as it was passed to the view.

If before you were passing in an object and relying on laratash converting it to an array, you'll just need to do that yourself now when creating the view.
